// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from "react";
import { Theme } from "./context";

export function rootContainer(rawContainer) {
  let container = rawContainer;
  container = <Theme rootContainer={container} />;
  return container;
}
