// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { ThemeProviderProps } from '/Users/congxiaochen/Desktop/demo/node_modules/.pnpm/antd-style@3.1.1_@types+react@18.2.6_antd@5.5.0_react-dom@18.2.0_react@18.2.0/node_modules/antd-style';
      export * from '/Users/congxiaochen/Desktop/demo/node_modules/.pnpm/antd-style@3.1.1_@types+react@18.2.6_antd@5.5.0_react-dom@18.2.0_react@18.2.0/node_modules/antd-style';
      export type RuntimeAntdStyleConfig = (
        memo: Omit<ThemeProviderProps<any>, "children">
      ) => Omit<ThemeProviderProps<any>, "children">;
